### PR TITLE
fix conventionnal name of license file

### PR DESCRIPTION
**Pull request by KevinTss**
If we avoid putting extension Normally github recognise it and turn it into a tab

### CODE REVIEW

**Comment by KevinTss** [comment]
@colevandersWands Do you want stick with LICENSE.md or do we merge this one?

**Comment by colevandersWands** [comment]
The license is written in markdown, that's why I used the extension.  Maybe it's best to stop using markdown licenses as a practice?

**Comment by KevinTss** [comment]
I just checked recommended way from github and apparently you have right using md 
My bad, I will close this issue

[Ressource link](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository#determining-the-location-of-your-license)

**Comment by colevandersWands** [comment]
I was right by accident, not complaining.

**Pull request closed without merging**
